import 'package:hive/hive.dart';
import 'package:linkdin_app/core/models/user_model.dart';
import 'package:intl/intl.dart'; // For date formatting

part 'comment_model.g.dart'; // This part file is generated by Hive

@HiveType(typeId: 2) // Assign a unique typeId to your model
class CommentModel extends HiveObject {
  @HiveField(0)
  final UserModel userModel;

  @HiveField(1)
  final String comment;

  @HiveField(2)
  final DateTime createdAt;

  CommentModel({
    required this.userModel,
    required this.comment,
    required this.createdAt,
  });

  // Getter for formatted date
  String get formattedCreatedAt {
    final DateFormat formatter = DateFormat('yyyy-MM-dd');
    return formatter.format(createdAt);
  }
}
